dataset<-read.table("~/Downloads/household_power_consumption.txt",header = T,sep = ";")
dataset$Date<-as.Date(dataset$Date,"%d/%m/%Y")
data<-subset(dataset,Date=="2007-02-01"|Date=="2007-02-02")
data$Time<-strptime(paste(data$Date,data$Time),format = "%Y-%m-%d %H:%M:%OS")
data$Global_active_power<-as.character(data$Global_active_power)
data$Global_active_power<-as.numeric(data$Global_active_power)
data$Sub_metering_1<-as.character(data$Sub_metering_1)
data$Sub_metering_1<-as.numeric(data$Sub_metering_1)
data$Sub_metering_2<-as.character(data$Sub_metering_2)
data$Sub_metering_2<-as.numeric(data$Sub_metering_2)
png(file="plot3.png")
with(data,plot(data$Time,Sub_metering_1,col="black",type="l",xlab="",ylab="Energy sub metering"))
lines(data$Time,data$Sub_metering_2,col="red",type="l")
lines(data$Time,data$Sub_metering_3,col="blue",type="l")
legend("topright",lty="solid",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()