dataset<-read.table("~/Downloads/household_power_consumption.txt",header = T,sep = ";")
dataset$Date<-as.Date(dataset$Date,"%d/%m/%Y")
data<-subset(dataset,Date=="2007-02-01"|Date=="2007-02-02")
data$Global_active_power<-as.character(data$Global_active_power)
data$Global_active_power<-as.numeric(data$Global_active_power)
png(file="plot2.png")
plot(data$Global_active_power,type = "l",ylab = "Global Active Power(kilowatts)",xlab = "",xaxt = "n")
axis(side = 1,at = c(0,1500,2900), labels = c("Thu","Fri","Sat"))
dev.off()
